---
# tasks file for jenkins

- name: Install Java 17 (Amazon Corretto)
  dnf:
    name: java-17-amazon-corretto-headless
    state: present

- name: Add Jenkins Repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins Key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

- name: Install Jenkins
  dnf:
    name: jenkins
    state: latest

- name: Start and Enable Jenkins
  service:
    name: jenkins
    state: started
    enabled: true
